/**
 * Generation service — section image generation, regeneration, editing and
 * section-version management.
 *
 * Ported from upstream `lib/services/generation-service.ts`
 * (ziguishian/MxPage, MIT, 灵矩绘境). See ../../NOTICE.
 *
 * Changes made during the DSH port:
 *  - The module-level exports became a factory: `createGenerationService(host, deps)`.
 *    No module-level singletons.
 *  - `import { prisma } from "@/lib/db/prisma"` → injected `host.repository`.
 *  - `getProviderAdapter()` (Prisma reads + an API key carried through
 *    `AsyncLocalStorage`) → `await host.provider.resolve(scope)` plus a
 *    per-call `new OpenAICompatibleAdapter(resolved.baseUrl, resolved.apiKey, logger)`.
 *  - `registerTaskAbortController` / `releaseTaskAbortController` /
 *    `assertTaskNotCanceled` come from the ported `createTaskService(host)`;
 *    `assertNotCanceled(taskSignal)` mirrors upstream's own cancellation
 *    checkpoints on the signal it threaded into fetch.
 *  - `assetToDataUrl` keeps reading bytes from disk, but through
 *    `assetStore.readStorageFile`.
 *  - `@prisma/client`'s `PageSection` / `ProductAsset` → domain types.
 *
 * Deliberately preserved verbatim (this file is mostly prompt + policy):
 * image-model ranking, the "do not rotate on quota/429/403/401" fallback
 * policy, the SVG fallback path, and every user-facing Chinese message.
 */

import { z } from "zod";

import { OpenAICompatibleAdapter } from "../ai/adapters/openai-compatible.ts";
import type { ProviderAdapter } from "../ai/provider-client.ts";
import {
  buildImageEditPrompt,
  buildRegenerationPrompt,
  buildSectionImagePrompt,
  buildSectionSvgLayoutPrompt,
} from "../ai/prompts/generation.ts";
import type { CoreHost } from "../ports/index.ts";
import { noopLogger } from "../ports/logger.ts";
import type { ProviderModelRecord, ProviderScope } from "../ports/provider.ts";
import { assertNotCanceled, isTaskCanceledError } from "../ports/tasks.ts";
import type { PageSection, ProductAsset, SectionVersion } from "../types/domain.ts";
import { sectionTypeLabels } from "../types/domain.ts";
import { normalizeContentLanguage, type ContentLanguage } from "../utils/content-language.ts";
import { buildDefaultVisualStyleGuide, readVisualStyleGuide } from "../utils/visual-style-guide.ts";
import { createAssetStore, type AssetStore } from "./asset-store.ts";
import { createTaskService, type TaskService } from "./task-service.ts";
import { buildVisualPromptWithAgent } from "./visual-prompt-agent.ts";

export const svgLayoutSchema = z.object({
  headline: z.string().min(1),
  subheadline: z.string().min(1),
  badge: z.string().min(1),
  highlights: z.array(z.string().min(1)).min(2).max(4),
  backgroundColor: z.string().min(4),
  accentColor: z.string().min(4),
  panelColor: z.string().min(4),
});

const svgCopyByLanguage: Partial<Record<
  ContentLanguage,
  {
    highlights: string;
    waitingForAsset: string;
    footer: string;
  }
>> = {
  "zh-CN": {
    highlights: "核心亮点",
    waitingForAsset: "等待商品图片素材",
    footer: "商品详情模块 · MxPage AI 自动生成",
  },
  "en-US": {
    highlights: "Key Highlights",
    waitingForAsset: "Waiting for product image",
    footer: "Product Detail Section · Auto-generated by MxPage AI",
  },
  "ja-JP": {
    highlights: "主なポイント",
    waitingForAsset: "商品画像を待っています",
    footer: "商品詳細セクション · MxPage AI 自動生成",
  },
  "ko-KR": {
    highlights: "핵심 포인트",
    waitingForAsset: "상품 이미지를 기다리는 중",
    footer: "상품 상세 섹션 · MxPage AI 자동 생성",
  },
};

type ProviderContext = { models: ProviderModelRecord[] };
type AdapterContext = ProviderAdapter;
type AssetRecord = Pick<ProductAsset, "id" | "filePath" | "fileName" | "mimeType" | "type" | "isMain">;
type SectionImageAspectRatio = "1:1" | "3:4" | "9:16";
type EditMode = "repaint" | "enhance" | "translate";
type GenerationMode = "image_api" | "svg_fallback";

/** Upstream returned versions with the `imageAsset` relation included. */
export type SectionVersionWithAsset = SectionVersion & { imageAsset: ProductAsset | null };

export interface SectionImageGenerationResult {
  imageAsset: ProductAsset;
  version: SectionVersion;
  usedModel: string;
  generationMode: GenerationMode;
}

export interface SectionImageEditResult extends SectionImageGenerationResult {
  editMode: EditMode;
  targetLanguage: ContentLanguage | undefined;
}

export interface EditSectionImageOptions {
  preferredModelId?: string | null;
  referenceAssetIds?: string[];
  editMode?: EditMode;
  targetLanguage?: ContentLanguage;
}

// ---------------------------------------------------------------------------
// Project / section settings readers (pure)
// ---------------------------------------------------------------------------

function getGenerationSettings(project: { modelSnapshot: unknown } | null) {
  const snapshot = (project?.modelSnapshot as Record<string, unknown> | null) ?? {};
  const settings = (snapshot.generationSettings as Record<string, unknown> | null) ?? {};
  const previewConfig = (snapshot.previewConfig as Record<string, unknown> | null) ?? {};

  return {
    allowSvgFallback: settings.allowSvgFallback === true,
    imageAspectRatio: previewConfig.imageAspectRatio === "3:4" ? "3:4" : "9:16",
    contentLanguage: normalizeContentLanguage(previewConfig.contentLanguage),
  } as {
    allowSvgFallback: boolean;
    imageAspectRatio: "3:4" | "9:16";
    contentLanguage: ContentLanguage;
  };
}

function getProjectVisualStyleGuide(project: { modelSnapshot: unknown; style?: string | null; platform?: string | null; analysis?: { normalizedResult: unknown } | null }) {
  const analysis = (project.analysis?.normalizedResult as Record<string, unknown> | null) ?? {};
  const fallback = buildDefaultVisualStyleGuide({
    productName: typeof analysis.productName === "string" ? analysis.productName : undefined,
    styleLabel: project.style ?? undefined,
    platformLabel: project.platform ?? undefined,
  });
  return readVisualStyleGuide(project.modelSnapshot, fallback) ?? fallback;
}

function readGenerationRequirements(analysis: unknown) {
  const value = (analysis as Record<string, unknown> | null)?.generationRequirements;
  return typeof value === "string" ? value : "";
}

function getSectionAspectRatio(
  section: Pick<PageSection, "type">,
  detailAspectRatio: "3:4" | "9:16",
): SectionImageAspectRatio {
  return section.type === "HERO" ? "1:1" : detailAspectRatio;
}

function getOutputSize(aspectRatio: SectionImageAspectRatio) {
  if (aspectRatio === "1:1") {
    return "1024x1024";
  }

  return "1024x1536";
}

// ---------------------------------------------------------------------------
// Image-model ranking / capability policy (pure, preserved verbatim)
// ---------------------------------------------------------------------------

function isStableImageModel(modelId: string) {
  return !/(preview|experimental|beta|test)/i.test(modelId);
}

function isPreferredImageModel(modelId: string) {
  return /(banana|nano-banana|nano banana|imagen|recraft|flux|gemini|gpt[-_\s]?image|chatgpt-image|dall[-_\s]?e|seedream|jimeng|midjourney|ideogram|hidream|kolors|wanx|cogview)/i.test(modelId);
}

function isGeminiImageModel(modelId: string) {
  return /gemini.*image|nano-banana|banana/i.test(modelId);
}

function isOpenAiGptImageModel(modelId: string) {
  return /(?:^|[-_\s])gpt[-_\s]?image(?:[-_\s]?(?:\d+(?:\.\d+)?|mini))?|chatgpt-image/i.test(modelId);
}

function readCapabilities(model: { capabilities: unknown }) {
  return (model.capabilities as Record<string, boolean> | null) ?? {};
}

function hasImageCapability(model: { capabilities: unknown }) {
  return Boolean(readCapabilities(model).image_gen);
}

function hasTextCapability(model: { capabilities: unknown }) {
  return Boolean(readCapabilities(model).text);
}

function hasVisionCapability(model: { capabilities: unknown }) {
  return Boolean(readCapabilities(model).vision);
}

function hasRealImageGeneration(model: { capabilities: unknown }) {
  return readCapabilities(model).real_image_gen !== false;
}

function hasRealImageEdit(model: { capabilities: unknown }) {
  return readCapabilities(model).real_image_edit !== false;
}

function canGenerateRealImage(model: { capabilities: unknown }) {
  const modelId = (model as { modelId?: string }).modelId ?? "";
  return hasImageCapability(model) && (hasRealImageGeneration(model) || isGeminiImageModel(modelId) || isOpenAiGptImageModel(modelId));
}

function canEditRealImage(model: { capabilities: unknown }) {
  const capabilities = readCapabilities(model);
  const modelId = (model as { modelId?: string }).modelId ?? "";
  return (
    (Boolean(capabilities.image_edit) && capabilities.real_image_edit !== false) ||
    (Boolean(capabilities.image_gen) &&
      (capabilities.real_image_gen !== false || isGeminiImageModel(modelId) || isOpenAiGptImageModel(modelId)))
  );
}

export function buildImageModelCandidates(
  provider: ProviderContext,
  options?: {
    preferredModelId?: string | null;
    regenerate?: boolean;
    edit?: boolean;
  },
) {
  const candidatePool = provider.models.filter((item) =>
    options?.edit ? canEditRealImage(item) : canGenerateRealImage(item),
  );

  const defaultKey = options?.edit
    ? "isDefaultImageEdit"
    : options?.regenerate
      ? "isDefaultDetailImage"
      : "isDefaultHeroImage";

  if (options?.preferredModelId) {
    return [options.preferredModelId];
  }

  const configuredDefault =
    candidatePool.find((item) => Boolean(item[defaultKey]))?.modelId ??
    (!options?.edit ? candidatePool.find((item) => item.isDefaultDetailImage)?.modelId : null);

  if (configuredDefault) {
    return [configuredDefault];
  }

  const candidates = [
    ...candidatePool
      .filter((item) => isStableImageModel(item.modelId) && isPreferredImageModel(item.modelId))
      .map((item) => item.modelId),
    ...candidatePool.filter((item) => isStableImageModel(item.modelId)).map((item) => item.modelId),
    ...candidatePool.filter((item) => isPreferredImageModel(item.modelId)).map((item) => item.modelId),
    ...candidatePool.map((item) => item.modelId),
  ].filter(Boolean) as string[];

  return [...new Set(candidates)];
}

export function buildSvgModelCandidates(provider: ProviderContext) {
  const visionText = provider.models.filter((item) => hasTextCapability(item) && hasVisionCapability(item));
  const textOnly = provider.models.filter((item) => hasTextCapability(item));

  const candidates = [
    provider.models.find((item) => item.isDefaultPlanning)?.modelId ?? null,
    provider.models.find((item) => item.isDefaultAnalysis)?.modelId ?? null,
    ...visionText
      .filter((item) => /gemini|gpt-4o|gpt-5/i.test(item.modelId) && !/preview|experimental|beta|test/i.test(item.modelId))
      .map((item) => item.modelId),
    ...visionText.filter((item) => !/preview|experimental|beta|test/i.test(item.modelId)).map((item) => item.modelId),
    ...textOnly
      .filter((item) => /gemini|gpt-4o|gpt-5/i.test(item.modelId) && !/preview|experimental|beta|test/i.test(item.modelId))
      .map((item) => item.modelId),
    ...textOnly.filter((item) => !/preview|experimental|beta|test/i.test(item.modelId)).map((item) => item.modelId),
    ...textOnly.map((item) => item.modelId),
  ].filter(Boolean) as string[];

  return [...new Set(candidates)];
}

// NOTE(dsh-port): known upstream flaw, preserved on purpose — an exhausted or
// mis-keyed channel makes this return false for quota / 429 / 403 / 401 /
// invalid-key failures, so `generateWithFallback` rethrows on the first such
// model instead of rotating to the next ranked candidate. Not silently fixed;
// the parent decides whether to change it.
export function shouldFallbackToNextImageModel(error: unknown) {
  if (!(error instanceof Error)) {
    return false;
  }

  if (
    /monthly spending limit|spending limit|billing|quota|insufficient_quota|403|forbidden|unauthorized|invalid token|api key|429|rate limit|限流/i.test(
      error.message,
    )
  ) {
    return false;
  }

  return /404|405|no available endpoint|unsupported|not implemented|does not exist|invalid_value|unknown parameter|invalid type|supported values|invalid value.+size/i.test(
    error.message,
  );
}

export function isTransientImageNetworkFailure(detail: string) {
  return /fetch failed|timed out|timeout|network error|socket hang up|ECONNRESET|ECONNREFUSED|ETIMEDOUT|ENOTFOUND/i.test(detail);
}

function buildTransientImageNetworkMessage(detail: string) {
  return "\u5f53\u524d\u56fe\u7247\u751f\u6210\u8bf7\u6c42\u7f51\u7edc\u5931\u8d25\u6216\u4ee3\u7406\u4e34\u65f6\u4e2d\u65ad\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5\u3002\u5f53\u524d\u6a21\u578b\u7aef\u70b9\u5df2\u5728\u672c\u8f6e\u751f\u6210\u4e2d\u6210\u529f\u8fd4\u56de\u8fc7\u56fe\u7247\uff0c\u8fd9\u4e0d\u662f Provider \u4e0d\u652f\u6301\u56fe\u7247\u751f\u6210\u3002\u539f\u59cb\u9519\u8bef\uff1a" + detail;
}

export function summarizeProviderImageFailure(detail: string, mode: "generate" | "edit") {
  const reasons: string[] = [];

  if (/model.+does not exist|invalid_value.+model/i.test(detail)) {
    reasons.push("代理商返回的图片模型名称无效或并不存在");
  }
  if (/no available endpoint|404/i.test(detail)) {
    reasons.push("代理商没有为这些模型开放真实图片端点");
  }
  if (/429|限流|rate limit/i.test(detail)) {
    reasons.push("代理商图片接口当前触发了限流");
  }
  if (/unknown parameter|invalid type|images\[0\]|supported values|invalid value.+size/i.test(detail)) {
    reasons.push("代理商图片接口的兼容格式与当前网关实现不一致");
  }

  if (!reasons.length) {
    reasons.push(mode === "edit" ? "图像编辑接口暂时不可用" : "图像生成接口暂时不可用");
  }

  return [...new Set(reasons)].join("；");
}

// ---------------------------------------------------------------------------
// SVG fallback helpers (pure, preserved verbatim)
// ---------------------------------------------------------------------------

function extractJsonBlock(raw: string) {
  const direct = raw.trim();
  if (direct.startsWith("{") || direct.startsWith("[")) {
    return direct;
  }

  const fencedMatch = direct.match(/```json([\s\S]*?)```/i) || direct.match(/```([\s\S]*?)```/i);
  if (fencedMatch?.[1]) {
    return fencedMatch[1].trim();
  }

  const firstBrace = direct.indexOf("{");
  const lastBrace = direct.lastIndexOf("}");
  if (firstBrace >= 0 && lastBrace > firstBrace) {
    return direct.slice(firstBrace, lastBrace + 1);
  }

  return direct;
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Upstream read the bytes off local disk; the port sources them through the
 * injected asset store (the driver owns the storage root).
 */
async function assetToDataUrl(assets: AssetStore, asset: Pick<AssetRecord, "filePath" | "mimeType">) {
  const buffer = await assets.readStorageFile(asset.filePath);
  const mimeType = asset.mimeType ?? "image/png";

  return `data:${mimeType};base64,${buffer.toString("base64")}`;
}

export function composeSectionSvg(params: {
  section: { title: string; copy: string; type: string };
  layout: z.infer<typeof svgLayoutSchema>;
  productImageDataUrl?: string | null;
  contentLanguage: ContentLanguage;
}) {
  const uiCopy = svgCopyByLanguage[params.contentLanguage] ?? svgCopyByLanguage["en-US"]!;
  const sectionLabel =
    sectionTypeLabels[params.section.type.toLowerCase() as keyof typeof sectionTypeLabels] ?? params.section.type;
  const highlights = params.layout.highlights
    .map(
      (item, index) => `
      <g transform="translate(${90 + (index % 2) * 390}, ${1160 + Math.floor(index / 2) * 100})">
        <rect rx="26" ry="26" width="330" height="72" fill="${params.layout.panelColor}" opacity="0.95" />
        <text x="28" y="45" font-size="30" fill="${params.layout.accentColor}" font-weight="700">${escapeXml(item)}</text>
      </g>`,
    )
    .join("");

  const productImage = params.productImageDataUrl
    ? `<image href="${params.productImageDataUrl}" x="110" y="350" width="860" height="700" preserveAspectRatio="xMidYMid meet" clip-path="url(#productClip)" />`
    : `<rect x="110" y="350" width="860" height="700" rx="56" fill="${params.layout.panelColor}" />
       <text x="540" y="720" text-anchor="middle" font-size="42" fill="${params.layout.accentColor}" font-weight="700">${escapeXml(uiCopy.waitingForAsset)}</text>`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="1080" height="1920" viewBox="0 0 1080 1920" fill="none" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1080" y2="1920" gradientUnits="userSpaceOnUse">
      <stop stop-color="${params.layout.backgroundColor}" />
      <stop offset="1" stop-color="#FFFFFF" />
    </linearGradient>
    <clipPath id="productClip">
      <rect x="110" y="350" width="860" height="700" rx="56" ry="56" />
    </clipPath>
  </defs>

  <rect width="1080" height="1920" fill="url(#bg)" />
  <circle cx="930" cy="250" r="150" fill="${params.layout.accentColor}" opacity="0.12" />
  <circle cx="170" cy="1460" r="220" fill="${params.layout.accentColor}" opacity="0.08" />

  <rect x="72" y="84" rx="28" ry="28" width="260" height="66" fill="${params.layout.accentColor}" />
  <text x="202" y="127" text-anchor="middle" font-size="28" fill="#FFFFFF" font-weight="700">${escapeXml(params.layout.badge)}</text>

  <text x="80" y="220" font-size="66" fill="#1F1720" font-weight="800">${escapeXml(params.layout.headline)}</text>
  <text x="80" y="292" font-size="34" fill="#5C515A" font-weight="500">${escapeXml(params.layout.subheadline)}</text>

  <g>
    <rect x="110" y="350" width="860" height="700" rx="56" fill="#FFFFFF" opacity="0.78" />
    ${productImage}
  </g>

  <rect x="72" y="1090" width="936" height="340" rx="44" fill="#FFFFFF" opacity="0.82" />
  <text x="112" y="1160" font-size="34" fill="#3A3139" font-weight="700">${escapeXml(uiCopy.highlights)}</text>
  ${highlights}

  <rect x="72" y="1468" width="936" height="280" rx="44" fill="${params.layout.panelColor}" opacity="0.98" />
  <text x="112" y="1540" font-size="34" fill="${params.layout.accentColor}" font-weight="800">${escapeXml(sectionLabel)}</text>
  <text x="112" y="1602" font-size="48" fill="#1F1720" font-weight="800">${escapeXml(params.section.title)}</text>
  <text x="112" y="1670" font-size="30" fill="#5A4E58" font-weight="500">${escapeXml(params.section.copy || params.layout.subheadline)}</text>

  <rect x="72" y="1788" width="936" height="88" rx="44" fill="${params.layout.accentColor}" />
  <text x="540" y="1844" text-anchor="middle" font-size="34" fill="#FFFFFF" font-weight="800">${escapeXml(uiCopy.footer)}</text>
</svg>`;
}

// ---------------------------------------------------------------------------
// Reference-asset selection (pure)
// ---------------------------------------------------------------------------

function pickPrimaryProductAsset(projectAssets: AssetRecord[]) {
  return (
    projectAssets.find((asset) => asset.isMain) ??
    projectAssets.find((asset) => asset.type === "MAIN") ??
    projectAssets.find((asset) => ["ANGLE", "DETAIL", "REFERENCE"].includes(asset.type)) ??
    projectAssets[0] ??
    null
  );
}

function mergeReferenceAssets(projectAssets: AssetRecord[], explicitReferenceAssets: AssetRecord[]) {
  const primaryAsset = pickPrimaryProductAsset(projectAssets);
  const merged = [primaryAsset, ...explicitReferenceAssets].filter(Boolean) as AssetRecord[];

  return merged.filter((asset, index, list) => list.findIndex((entry) => entry.id === asset.id) === index);
}

/**
 * Upstream relied on Prisma's `orderBy: [{ isMain: "desc" }, { sortOrder: "asc" },
 * { createdAt: "asc" }]` on `Project.assets`. The Repository port does not
 * promise an ordering for `getDetail`, so it is re-applied here.
 */
function orderProjectAssets(projectAssets: ProductAsset[]) {
  return [...projectAssets].sort(
    (a, b) =>
      Number(b.isMain) - Number(a.isMain) ||
      a.sortOrder - b.sortOrder ||
      a.createdAt.getTime() - b.createdAt.getTime(),
  );
}

// ---------------------------------------------------------------------------
// Fallback loops (pure, preserved verbatim)
// ---------------------------------------------------------------------------

async function generateWithFallback(params: {
  adapter: AdapterContext;
  candidateModels: string[];
  prompt: string;
  size: string;
  aspectRatio: SectionImageAspectRatio;
  referenceImages: string[];
  projectId: string;
  sectionId: string;
  operation: string;
  signal?: AbortSignal;
}) {
  const errors: string[] = [];

  for (const model of params.candidateModels) {
    try {
      const generated = await params.adapter.generateImage({
        model,
        prompt: params.prompt,
        size: params.size,
        aspectRatio: params.aspectRatio,
        referenceImages: params.referenceImages,
        monitor: {
          projectId: params.projectId,
          sectionId: params.sectionId,
          operation: params.operation,
        },
        signal: params.signal,
      });

      return {
        model,
        generated,
        attemptedModels: params.candidateModels,
      };
    } catch (error) {
      if (isTaskCanceledError(error)) throw error;
      const message = error instanceof Error ? error.message : "Unknown image generation error";
      errors.push(`${model}: ${message}`);

      if (!shouldFallbackToNextImageModel(error)) {
        throw error;
      }
    }
  }

  throw new Error(`所有可用图片模型都生成失败：${errors.join(" | ")}`);
}

async function editWithFallback(params: {
  adapter: AdapterContext;
  candidateModels: string[];
  prompt: string;
  image: string;
  size: string;
  aspectRatio: SectionImageAspectRatio;
  referenceImages: string[];
  projectId: string;
  sectionId: string;
  operation: string;
  signal?: AbortSignal;
}) {
  const errors: string[] = [];

  for (const model of params.candidateModels) {
    try {
      const generated = await params.adapter.editImage({
        model,
        prompt: params.prompt,
        image: params.image,
        size: params.size,
        aspectRatio: params.aspectRatio,
        referenceImages: params.referenceImages,
        monitor: {
          projectId: params.projectId,
          sectionId: params.sectionId,
          operation: params.operation,
        },
        signal: params.signal,
      });

      return {
        model,
        generated,
        attemptedModels: params.candidateModels,
      };
    } catch (error) {
      if (isTaskCanceledError(error)) throw error;
      const message = error instanceof Error ? error.message : "Unknown image edit error";
      errors.push(`${model}: ${message}`);

      if (!shouldFallbackToNextImageModel(error)) {
        throw error;
      }
    }
  }

  throw new Error(`所有可用图片编辑模型都处理失败：${errors.join(" | ")}`);
}

async function generateSvgLayoutSpec(params: {
  adapter: AdapterContext;
  candidateModels: string[];
  userPrompt: string;
  images: string[];
  projectId: string;
  sectionId: string;
  operation: string;
  signal?: AbortSignal;
}) {
  const errors: string[] = [];

  for (const model of params.candidateModels) {
    try {
      const result = await params.adapter.generateText({
        model,
        systemPrompt: "Return one strict JSON object only. No markdown.",
        userPrompt: params.userPrompt,
        images: params.images,
        monitor: {
          projectId: params.projectId,
          sectionId: params.sectionId,
          operation: params.operation,
        },
        signal: params.signal,
      });

      const parsed = svgLayoutSchema.parse(JSON.parse(extractJsonBlock(result.text)));
      return {
        model,
        parsed,
      };
    } catch (error) {
      if (isTaskCanceledError(error)) throw error;
      errors.push(`${model}: ${error instanceof Error ? error.message : "Unknown SVG layout error"}`);
    }
  }

  throw new Error(`SVG 版式生成失败：${errors.join(" | ")}`);
}

async function generateSvgFallback(params: {
  section: PageSection;
  adapter: AdapterContext;
  provider: ProviderContext;
  assets: AssetStore;
  referenceAssets: AssetRecord[];
  aspectRatio: SectionImageAspectRatio;
  contentLanguage: ContentLanguage;
  signal?: AbortSignal;
}) {
  const modelCandidates = buildSvgModelCandidates(params.provider);
  if (!modelCandidates.length) {
    throw new Error("当前 Provider 没有可用于 SVG 兜底预览的文本模型。");
  }

  const selectedAssets = params.referenceAssets.slice(0, 4);
  const imageInputs = await Promise.all(selectedAssets.map((asset) => assetToDataUrl(params.assets, asset)));
  const layoutSpec = await generateSvgLayoutSpec({
    adapter: params.adapter,
    candidateModels: modelCandidates,
    userPrompt: buildSectionSvgLayoutPrompt(
      params.section,
      params.referenceAssets as ProductAsset[],
      params.aspectRatio,
      params.contentLanguage,
    ),
    images: imageInputs,
    projectId: params.section.projectId,
    sectionId: params.section.id,
    operation: "svg_fallback_layout",
    signal: params.signal,
  });

  const productImageAsset = params.referenceAssets[0] ?? null;
  const productImageDataUrl = productImageAsset ? await assetToDataUrl(params.assets, productImageAsset) : null;
  const svgText = composeSectionSvg({
    section: {
      title: params.section.title,
      copy: params.section.copy,
      type: params.section.type,
    },
    layout: layoutSpec.parsed,
    productImageDataUrl,
    contentLanguage: params.contentLanguage,
  });

  return {
    svgText,
    model: layoutSpec.model,
    layout: layoutSpec.parsed,
  };
}

// ---------------------------------------------------------------------------
// Service factory
// ---------------------------------------------------------------------------

export interface GenerationServiceDeps {
  /** Pre-built asset store. Defaults to `createAssetStore(host)`. */
  assets?: AssetStore;
  /** Pre-built task service. Defaults to `createTaskService(host)`. */
  tasks?: TaskService;
}

export interface GenerationService {
  generateSectionImage(
    projectId: string,
    sectionId: string,
    preferredModelId?: string | null,
    referenceAssetIds?: string[],
    onTaskCreated?: (taskId: string) => void | Promise<void>,
  ): Promise<SectionImageGenerationResult>;
  regenerateSectionImage(
    projectId: string,
    sectionId: string,
    preferredModelId?: string | null,
    referenceAssetIds?: string[],
    onTaskCreated?: (taskId: string) => void | Promise<void>,
  ): Promise<SectionImageGenerationResult>;
  editSectionImage(
    projectId: string,
    sectionId: string,
    options?: EditSectionImageOptions,
  ): Promise<SectionImageEditResult>;
  listSectionVersions(sectionId: string): Promise<SectionVersionWithAsset[]>;
  activateSectionVersion(sectionId: string, versionId: string): Promise<SectionVersionWithAsset | null>;
  /** Upstream's local `persistSectionVersion`, exposed because it is shared policy. */
  persistSectionVersion(params: {
    sectionId: string;
    imageAssetId: string;
    promptSnapshot: string;
    copySnapshot: string;
  }): Promise<SectionVersion>;
}

export function createGenerationService(
  host: CoreHost,
  deps: GenerationServiceDeps = {},
): GenerationService {
  const { repository } = host;
  const logger = host.logger ?? noopLogger;
  const assets = deps.assets ?? createAssetStore(host);
  const tasks = deps.tasks ?? createTaskService(host);

  /** Upstream `getProviderAdapter()`, reduced to the two ports that own it. */
  async function resolveProviderAdapter(scope: ProviderScope) {
    const resolved = await host.provider.resolve(scope);
    const adapter = new OpenAICompatibleAdapter(resolved.baseUrl, resolved.apiKey, logger);
    const provider: ProviderContext = { models: resolved.models };

    return { provider, adapter };
  }

  /**
   * Upstream `prisma.productAsset.findMany({ where: { id: { in: ids } } })`.
   * The Repository port exposes per-id reads instead of an id-set filter, so the
   * requested order is preserved (upstream returned DB order, which nothing
   * downstream depended on — `mergeReferenceAssets` re-ranks by primary asset).
   * Like upstream, this is NOT project-scoped.
   */
  async function resolveReferenceAssets(referenceAssetIds: string[]): Promise<ProductAsset[]> {
    if (!referenceAssetIds.length) {
      return [];
    }

    const uniqueIds = [...new Set(referenceAssetIds)];
    const found = await Promise.all(uniqueIds.map((id) => repository.asset.get(id)));

    return found.filter((asset): asset is ProductAsset => Boolean(asset));
  }

  /**
   * Upstream `persistSectionVersion`: read the last `versionNumber`, mark every
   * sibling inactive, then create the next active version.
   */
  async function persistSectionVersion(params: {
    sectionId: string;
    imageAssetId: string;
    promptSnapshot: string;
    copySnapshot: string;
  }) {
    const versionNumber = await repository.version.nextVersionNumber(params.sectionId);

    const created = await repository.version.create({
      sectionId: params.sectionId,
      versionNumber,
      promptSnapshot: { prompt: params.promptSnapshot },
      copySnapshot: { copy: params.copySnapshot },
      imageAssetId: params.imageAssetId,
    });

    // `CreateVersionInput` carries no `isActive`, so the port cannot express
    // "deactivate siblings + activate this one" in `create` alone. Upstream's
    // invariant is enforced through `setActive` whenever `create` did not
    // already return an active version.
    if (!created.isActive) {
      return repository.version.setActive(params.sectionId, created.id);
    }

    return created;
  }

  async function listSectionVersions(sectionId: string): Promise<SectionVersionWithAsset[]> {
    const versions = await repository.version.list(sectionId);
    const ordered = [...versions].sort((a, b) => b.versionNumber - a.versionNumber);

    return Promise.all(
      ordered.map(async (version) => ({
        ...version,
        imageAsset: version.imageAssetId ? await repository.asset.get(version.imageAssetId) : null,
      })),
    );
  }

  async function activateSectionVersion(sectionId: string, versionId: string): Promise<SectionVersionWithAsset | null> {
    const version = await repository.version.get(versionId);

    if (!version || version.sectionId !== sectionId) {
      throw new Error("Version not found.");
    }

    // Upstream: `updateMany({ isActive: false })` + `update({ isActive: true })`.
    await repository.version.setActive(sectionId, versionId);

    await repository.section.update(sectionId, {
      currentImageAssetId: version.imageAssetId ?? null,
      status: "SUCCESS",
    });

    const activated = await repository.version.get(versionId);
    if (!activated) {
      return null;
    }

    return {
      ...activated,
      imageAsset: activated.imageAssetId ? await repository.asset.get(activated.imageAssetId) : null,
    };
  }

  async function generateSectionImageInternal(
    projectId: string,
    sectionId: string,
    options?: {
      preferredModelId?: string | null;
      referenceAssetIds?: string[];
      regenerate?: boolean;
      onTaskCreated?: (taskId: string) => void | Promise<void>;
    },
  ): Promise<SectionImageGenerationResult> {
    const project = await repository.project.getDetail(projectId);

    const section = await repository.section.get(sectionId);

    if (!project) {
      throw new Error("Project not found.");
    }

    if (!section || section.projectId !== projectId) {
      throw new Error("Section not found.");
    }

    const projectAssets = orderProjectAssets(project.assets);

    const runningTask = await tasks.findRecentRunningTask({
      projectId,
      sectionId,
      taskType: options?.regenerate ? "REGENERATE" : "GENERATE",
      maxAgeMinutes: 20,
    });
    if (runningTask) {
      throw new Error("当前模块图仍在生成中，请等待这一轮完成后再试。");
    }

    const task = await tasks.createTask({
      projectId,
      sectionId,
      taskType: options?.regenerate ? "REGENERATE" : "GENERATE",
      inputPayload: {
        referenceAssetIds: options?.referenceAssetIds ?? [],
        regenerate: Boolean(options?.regenerate),
      },
    });
    const taskSignal = tasks.registerTaskAbortController(task.id);

    try {
      await options?.onTaskCreated?.(task.id);
      await repository.section.update(sectionId, { status: "GENERATING" });
      await tasks.assertTaskNotCanceled(task.id);
      assertNotCanceled(taskSignal);

      const { provider, adapter } = await resolveProviderAdapter({
        projectId,
        sectionId,
        operation: options?.regenerate ? "regenerate_section_image" : "generate_section_image",
      });
      const generationSettings = getGenerationSettings(project);
      const visualStyleGuide = getProjectVisualStyleGuide(project);
      const generationRequirements = readGenerationRequirements(project.analysis?.normalizedResult);
      const sectionAspectRatio = getSectionAspectRatio(section, generationSettings.imageAspectRatio);
      const outputSize = getOutputSize(sectionAspectRatio);
      const modelCandidates = buildImageModelCandidates(provider, options);
      const selectedModel = modelCandidates[0] ?? null;
      const explicitReferenceAssets = await resolveReferenceAssets(options?.referenceAssetIds ?? []);
      const effectiveReferenceAssets = mergeReferenceAssets(
        projectAssets as AssetRecord[],
        explicitReferenceAssets as AssetRecord[],
      );
      const referenceImages = await Promise.all(
        effectiveReferenceAssets.map((asset) => assetToDataUrl(assets, asset)),
      );
      await tasks.assertTaskNotCanceled(task.id);
      assertNotCanceled(taskSignal);

      const basePrompt = options?.regenerate
        ? buildRegenerationPrompt(
            section,
            effectiveReferenceAssets as ProductAsset[],
            sectionAspectRatio,
            generationSettings.contentLanguage,
            generationRequirements,
          )
        : buildSectionImagePrompt(
            section,
            effectiveReferenceAssets as ProductAsset[],
            sectionAspectRatio,
            generationSettings.contentLanguage,
            generationRequirements,
          );
      const prompt = await buildVisualPromptWithAgent({
        provider,
        adapter,
        mode: "ecommerce_section",
        title: section.title,
        goal: section.goal,
        copy: section.copy,
        basePrompt,
        aspectRatio: sectionAspectRatio,
        contentLanguage: generationSettings.contentLanguage,
        referenceImages,
        referenceAssets: effectiveReferenceAssets as ProductAsset[],
        productContext: project.analysis?.normalizedResult ?? project.modelSnapshot ?? null,
        visualStyleGuide,
        projectId,
        sectionId,
        operation: options?.regenerate ? "visual_prompt_agent_regenerate_section" : "visual_prompt_agent_generate_section",
        signal: taskSignal,
      });
      await tasks.assertTaskNotCanceled(task.id);
      assertNotCanceled(taskSignal);

      let imageAsset;
      let version;
      let usedModel: string;
      let generationMode: GenerationMode;

      try {
        if (!selectedModel) {
          throw new Error("当前 Provider 没有识别到可用于真实图片生成的模型。");
        }

        const generation = await generateWithFallback({
          adapter,
          candidateModels: modelCandidates,
          prompt,
          size: outputSize,
          aspectRatio: sectionAspectRatio,
          referenceImages,
          projectId,
          sectionId,
          operation: options?.regenerate ? "regenerate_section_image" : "generate_section_image",
          signal: taskSignal,
        });
        await tasks.assertTaskNotCanceled(task.id);
        assertNotCanceled(taskSignal);

        imageAsset = await assets.saveGeneratedImage({
          projectId,
          sectionId,
          prompt,
          source: generation.generated,
          metadata: {
            mode: "image_api",
            usedModel: generation.model,
            sourceReferenceAssetIds: effectiveReferenceAssets.map((asset) => asset.id),
            primaryReferenceAssetId: effectiveReferenceAssets[0]?.id ?? null,
          },
        });
        await tasks.assertTaskNotCanceled(task.id);
        assertNotCanceled(taskSignal);

        usedModel = generation.model;
        generationMode = "image_api";
      } catch (error) {
        if (isTaskCanceledError(error)) throw error;
        if (!generationSettings.allowSvgFallback) {
          const detail = error instanceof Error ? error.message : "Unknown image generation error";
          if (/monthly spending limit|spending limit|billing|quota/i.test(detail)) {
            throw new Error("当前 API Key 的图片生成额度已用尽。请前往代理商控制台提高或移除月度限额，或更换可用的 API Key。");
          }
          if (isTransientImageNetworkFailure(detail)) {
            throw new Error(buildTransientImageNetworkMessage(detail));
          }
          const summary = summarizeProviderImageFailure(detail, "generate");
          throw new Error(
            `当前 Provider 没有可用的真实图片生成端点。请前往“模型服务配置”页更换支持图片生成的 Provider，或在规划页手动开启“允许 SVG 兜底预览”。原因摘要：${summary}`,
          );
        }

        const fallback = await generateSvgFallback({
          section,
          adapter,
          provider,
          assets,
          referenceAssets: effectiveReferenceAssets,
          aspectRatio: sectionAspectRatio,
          contentLanguage: generationSettings.contentLanguage,
          signal: taskSignal,
        });
        await tasks.assertTaskNotCanceled(task.id);
        assertNotCanceled(taskSignal);

        imageAsset = await assets.saveGeneratedImage({
          projectId,
          sectionId,
          prompt,
          source: {
            svgText: fallback.svgText,
            mimeType: "image/svg+xml",
          },
          metadata: {
            mode: "svg_fallback",
            usedModel: fallback.model,
            layout: fallback.layout,
            sourceReferenceAssetIds: effectiveReferenceAssets.map((asset) => asset.id),
            primaryReferenceAssetId: effectiveReferenceAssets[0]?.id ?? null,
            imageApiError: error instanceof Error ? error.message : "Unknown image api error",
          },
        });
        await tasks.assertTaskNotCanceled(task.id);
        assertNotCanceled(taskSignal);

        usedModel = fallback.model;
        generationMode = "svg_fallback";
      }

      version = await persistSectionVersion({
        sectionId,
        imageAssetId: imageAsset.id,
        promptSnapshot: prompt,
        copySnapshot: section.copy,
      });

      await repository.section.update(sectionId, {
        status: "SUCCESS",
        currentImageAssetId: imageAsset.id,
      });

      await repository.project.update(projectId, {
        status: "EDITING",
      });

      await tasks.completeTask(task.id, {
        imageAssetId: imageAsset.id,
        versionId: version.id,
        usedModel,
        generationMode,
        sourceReferenceAssetIds: effectiveReferenceAssets.map((asset) => asset.id),
      });

      return { imageAsset, version, usedModel, generationMode };
    } catch (error) {
      await repository.section.update(sectionId, {
        status: isTaskCanceledError(error) ? (section.currentImageAssetId ? "SUCCESS" : "IDLE") : "FAILED",
      });

      if (!isTaskCanceledError(error)) {
        await tasks.failTask(task.id, error instanceof Error ? error.message : "Image generation failed");
      }
      throw error;
    } finally {
      tasks.releaseTaskAbortController(task.id);
    }
  }

  async function generateSectionImage(
    projectId: string,
    sectionId: string,
    preferredModelId?: string | null,
    referenceAssetIds?: string[],
    onTaskCreated?: (taskId: string) => void | Promise<void>,
  ) {
    return generateSectionImageInternal(projectId, sectionId, {
      preferredModelId,
      referenceAssetIds,
      regenerate: false,
      onTaskCreated,
    });
  }

  async function regenerateSectionImage(
    projectId: string,
    sectionId: string,
    preferredModelId?: string | null,
    referenceAssetIds?: string[],
    onTaskCreated?: (taskId: string) => void | Promise<void>,
  ) {
    return generateSectionImageInternal(projectId, sectionId, {
      preferredModelId,
      referenceAssetIds,
      regenerate: true,
      onTaskCreated,
    });
  }

  async function editSectionImage(
    projectId: string,
    sectionId: string,
    options?: EditSectionImageOptions,
  ): Promise<SectionImageEditResult> {
    const project = await repository.project.getDetail(projectId);

    const section = await repository.section.get(sectionId);

    if (!project) {
      throw new Error("Project not found.");
    }

    if (!section || section.projectId !== projectId) {
      throw new Error("Section not found.");
    }

    // Upstream `include: { currentImageAsset: true }`.
    const currentImageAsset = section.currentImageAssetId
      ? await repository.asset.get(section.currentImageAssetId)
      : null;

    if (!currentImageAsset) {
      throw new Error("当前模块还没有可编辑的底图，请先生成一张模块图。");
    }

    const { provider, adapter } = await resolveProviderAdapter({
      projectId,
      sectionId,
      operation: "edit_section_image",
    });
    const generationSettings = getGenerationSettings(project);
    const visualStyleGuide = getProjectVisualStyleGuide(project);
    const generationRequirements = readGenerationRequirements(project.analysis?.normalizedResult);
    const sectionAspectRatio = getSectionAspectRatio(section, generationSettings.imageAspectRatio);
    const outputSize = getOutputSize(sectionAspectRatio);
    const modelCandidates = buildImageModelCandidates(provider, {
      preferredModelId: options?.preferredModelId,
      edit: true,
      regenerate: true,
    });
    const selectedModel = modelCandidates[0] ?? null;
    const explicitReferenceAssets = await resolveReferenceAssets(options?.referenceAssetIds ?? []);
    const productReferenceAssets = mergeReferenceAssets(
      orderProjectAssets(project.assets) as AssetRecord[],
      explicitReferenceAssets as AssetRecord[],
    );
    const baseImage = await assetToDataUrl(assets, currentImageAsset as AssetRecord);
    const referenceImages = await Promise.all(
      productReferenceAssets
        .filter((asset) => asset.id !== section.currentImageAssetId)
        .map((asset) => assetToDataUrl(assets, asset)),
    );
    const editMode = options?.editMode ?? "repaint";
    const effectiveContentLanguage = editMode === "translate" ? normalizeContentLanguage(options?.targetLanguage) : generationSettings.contentLanguage;
    const runningTask = await tasks.findRecentRunningTask({
      projectId,
      sectionId,
      taskType: "REGENERATE",
      maxAgeMinutes: 20,
    });
    if (runningTask) {
      throw new Error("当前模块图仍在重绘或增强中，请等待这一轮完成后再试。");
    }

    const task = await tasks.createTask({
      projectId,
      sectionId,
      taskType: "REGENERATE",
      inputPayload: {
        mode: "edit_image",
        editMode,
        targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined,
        model: selectedModel,
        modelCandidates,
        baseImageAssetId: section.currentImageAssetId,
        referenceAssetIds: options?.referenceAssetIds ?? [],
        effectiveReferenceAssetIds: productReferenceAssets.map((asset) => asset.id),
        allowSvgFallback: generationSettings.allowSvgFallback,
      },
    });

    await repository.section.update(sectionId, { status: "GENERATING" });

    // NOTE(dsh-port): upstream `editSectionImage` never called
    // `registerTaskAbortController` / `assertTaskNotCanceled` and never threaded
    // a signal, so this path is NOT cooperatively cancellable (unlike
    // generate/regenerate) and there is no `releaseTaskAbortController` in a
    // `finally`. Preserved as-is rather than silently changed; flagged for the
    // parent to decide.
    try {
      const basePrompt = buildImageEditPrompt(
        section,
        productReferenceAssets as ProductAsset[],
        editMode,
        sectionAspectRatio,
        effectiveContentLanguage,
        generationRequirements,
      );
      const prompt = await buildVisualPromptWithAgent({
        provider,
        adapter,
        mode: "image_edit",
        title: section.title,
        goal: section.goal,
        copy: section.copy,
        basePrompt,
        aspectRatio: sectionAspectRatio,
        contentLanguage: effectiveContentLanguage,
        referenceImages: [baseImage, ...referenceImages],
        referenceAssets: productReferenceAssets as ProductAsset[],
        productContext: project.analysis?.normalizedResult ?? project.modelSnapshot ?? null,
        visualStyleGuide,
        projectId,
        sectionId,
        operation: editMode === "translate" ? "visual_prompt_agent_translate_section" : editMode === "enhance" ? "visual_prompt_agent_enhance_section" : "visual_prompt_agent_repaint_section",
      });

      let imageAsset;
      let version;
      let usedModel: string;
      let generationMode: GenerationMode;

      try {
        if (!selectedModel) {
          throw new Error("当前 Provider 没有识别到可用于真实图片编辑的模型。");
        }

        const generation = await editWithFallback({
          adapter,
          candidateModels: modelCandidates,
          prompt,
          image: baseImage,
          size: outputSize,
          aspectRatio: sectionAspectRatio,
          referenceImages,
          projectId,
          sectionId,
          operation: editMode === "translate" ? "translate_section_image" : editMode === "enhance" ? "enhance_section_image" : "repaint_section_image",
        });

        imageAsset = await assets.saveGeneratedImage({
          projectId,
          sectionId,
          prompt,
          source: generation.generated,
          metadata: {
            mode: "image_api",
            usedModel: generation.model,
            editMode,
            targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined,
            baseImageAssetId: section.currentImageAssetId,
            sourceReferenceAssetIds: productReferenceAssets.map((asset) => asset.id),
            primaryReferenceAssetId: productReferenceAssets[0]?.id ?? null,
          },
        });

        usedModel = generation.model;
        generationMode = "image_api";
      } catch (error) {
        if (!generationSettings.allowSvgFallback) {
          const detail = error instanceof Error ? error.message : "Unknown image edit error";
          if (/monthly spending limit|spending limit|billing|quota/i.test(detail)) {
            throw new Error("当前 API Key 的图片编辑/生成额度已用尽。请前往代理商控制台提高或移除月度限额，或更换可用的 API Key。");
          }
          if (isTransientImageNetworkFailure(detail)) {
            throw new Error(buildTransientImageNetworkMessage(detail));
          }
          const summary = summarizeProviderImageFailure(detail, "edit");
          throw new Error(
            `当前 Provider 没有可用的真实图片生成或编辑端点。请前往“模型服务配置”页更换支持图片编辑的 Provider，或在规划页手动开启“允许 SVG 兜底预览”。原因摘要：${summary}`,
          );
        }

        const fallback = await generateSvgFallback({
          section,
          adapter,
          provider,
          assets,
          referenceAssets: productReferenceAssets,
          aspectRatio: sectionAspectRatio,
          contentLanguage: generationSettings.contentLanguage,
        });

        imageAsset = await assets.saveGeneratedImage({
          projectId,
          sectionId,
          prompt,
          source: {
            svgText: fallback.svgText,
            mimeType: "image/svg+xml",
          },
          metadata: {
            mode: "svg_fallback",
            usedModel: fallback.model,
            editMode,
            targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined,
            baseImageAssetId: section.currentImageAssetId,
            layout: fallback.layout,
            sourceReferenceAssetIds: productReferenceAssets.map((asset) => asset.id),
            primaryReferenceAssetId: productReferenceAssets[0]?.id ?? null,
            imageApiError: error instanceof Error ? error.message : "Unknown image edit api error",
          },
        });

        usedModel = fallback.model;
        generationMode = "svg_fallback";
      }

      version = await persistSectionVersion({
        sectionId,
        imageAssetId: imageAsset.id,
        promptSnapshot: prompt,
        copySnapshot: section.copy,
      });

      await repository.section.update(sectionId, {
        status: "SUCCESS",
        currentImageAssetId: imageAsset.id,
      });

      await repository.project.update(projectId, {
        status: "EDITING",
      });

      await tasks.completeTask(task.id, {
        mode: "edit_image",
        editMode,
        targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined,
        imageAssetId: imageAsset.id,
        versionId: version.id,
        usedModel,
        generationMode,
        baseImageAssetId: section.currentImageAssetId,
        sourceReferenceAssetIds: productReferenceAssets.map((asset) => asset.id),
      });

      return { imageAsset, version, usedModel, generationMode, editMode, targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined };
    } catch (error) {
      await repository.section.update(sectionId, {
        status: "FAILED",
      });

      await tasks.failTask(task.id, error instanceof Error ? error.message : "Image edit failed");
      throw error;
    }
  }

  return {
    generateSectionImage,
    regenerateSectionImage,
    editSectionImage,
    listSectionVersions,
    activateSectionVersion,
    persistSectionVersion,
  };
}
